#!/bin/zsh

nbmerge *.ipynb(n) | jupyter nbconvert --execute --to=notebook --stdin --stdout --log-level=ERROR > merged.ipynb
# templates: base, article, report
jupyter nbconvert --to pdf --template article merged.ipynb --output-dir=../report
rm merged.ipynb
